[package]
name = "tauri-http-client-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.149"
tauri = "2.9.5"
tauri-plugin-http = "2.5.4"
tauri-plugin-log = "2.7.1"
tokio = { version = "1.41", features = ["macros", "rt-multi-thread"] }
mockito = "1.7"
